/*
** Class for displaying Warning message until future method makes calculation for 
** federal and state/local taxes on Zuora Quote Object.
*/
public with sharing class clsZuoraQuoteInfo {
    /*public String imgPath{get;set;}
    public Boolean warn1{get;set;}
    private zqu__Quote__c quoteRec ;

    public clsZuoraQuoteInfo(ApexPages.StandardController controller) {
        /*this.quoteRec = (zqu__Quote__c)controller.getRecord();
        ImgPath = '/resource/warning';
        for(zqu__Quote__c zQuote: [SELECT id,Zuora_Calculating_tax__c FROM zqu__Quote__c WHERE Id =:quoteRec.id LIMIT 1] ){    
            try{
                if(zQuote.Zuora_Calculating_tax__c == true){
                    warn1=true;
               }
            }catch(Exception e){}
        } 
    }*/
}