/*************************************************
LeadSearchController class
Along with LeadSearchPage.page allows users to search for existing leads and opp's based on contact information
Shows results broken up by main defining factor of protected or not protected.
If all fields are available the search will use last name, company, email and phone to match existing records
/************************************************/
public class LeadSearchController {
   
    public LeadSearchController(ApexPages.StandardController controller) {
     
    }
}