public class UserJsonObject{
	
	public UserJsonObject() {
		
	}
	
  /* @isTest(SeeAllData=true)
   static  void UserJsonObjectTest0() {
   		UserJsonObject userObj = new UserJsonObject();
   }

 public String id{get;set;}
 public String asserted_user{get;set;}
 public String user_id{get;set;}
 public String organization_id{get;set;}
 public String username{get;set;}
 public String nick_name{get;set;}
 public String display_name{get;set;}
 public String email{get;set;}
 public String first_name{get;set;}
 public String last_name{get;set;}
 public innerStatusObject status{get;set;}
 public innerPhotoObject photos{get;set;}
 public innerUrlObject urls{get;set;}
 public Boolean active{get;set;}
 public String user_type{get;set;}
 public String language{get;set;}
 public String locale{get;set;}
 public String utcOffset{get;set;}
 public String last_modified_date{get;set;}*/
 

//private class innerStatusObject{
  //String created_date{get;set;}
  //String body{get;set;}
//}
//public class  innerPhotoObject{
  //public String picture{get;set;}
  //public String thumbnail{get;set;}
//}
//public class  innerUrlObject{
 /* String enterprise{get;set;}
  String metadata{get;set;}
  String partner{get;set;}
  String rest{get;set;}
  String sobjects{get;set;}
  String search{get;set;}
  String query{get;set;}
  String recent{get;set;}
  public String profile{get;set;}
  String feeds{get;set;}
  String groups{get;set;}
  String users{get;set;}
  String feed_items{get;set;}
  String custom_domain{get;set;}*/
//}

     /*public UserJsonObject(String user_id,String organization_id,String username,String nick_name, String display_name, String email, String first_name,
                            String last_name,List<innerStatusObject> status,List<innerPhotoObject> photos,List<innerUrlObject> urls,Boolean active,  String user_type,  String language,  String locale,   String utcOffset,    String last_modified_date){
     
     this.user_id=user_id;
     this.organization_id=organization_id;
     this.username=username;
     this.nick_name=nick_name;
     this.display_name=display_name;
     this.email=email;
     this.first_name=first_name;
     this.last_name=last_name ;
     this.active=active;
     this.user_type=user_type;
     this.language=language;
     this.locale=locale;
     this.utcOffset=utcOffset;
     this.last_modified_date=last_modified_date;
     this.status=status;
     this.photos=photos;
     this.urls=urls;
     } */
}